# Python package

# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.3'
  

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
  
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      make install-build-tools
  displayName: 'Installing build Tools'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      make clean
  displayName: 'Clean out systems'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      make build
  displayName: 'Build Package'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      make test
  displayName: 'Run unit tests'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      twine check dist/*
  displayName: 'Validate Release'
